apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: student-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: student-api
    spec:
      containers:
      - name: student-api
        image: blazerodrigues/student-api
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD